// @generated
// This file was automatically generated and should not be edited.

import ApolloAPI

public typealias ID = String

public protocol SelectionSet: ApolloAPI.SelectionSet & ApolloAPI.RootSelectionSet
where Schema == GitHubGraphQLAPI.SchemaMetadata {}

public protocol InlineFragment: ApolloAPI.SelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubGraphQLAPI.SchemaMetadata {}

public protocol MutableSelectionSet: ApolloAPI.MutableRootSelectionSet
where Schema == GitHubGraphQLAPI.SchemaMetadata {}

public protocol MutableInlineFragment: ApolloAPI.MutableSelectionSet & ApolloAPI.InlineFragment
where Schema == GitHubGraphQLAPI.SchemaMetadata {}

public enum SchemaMetadata: ApolloAPI.SchemaMetadata {
  public static let configuration: ApolloAPI.SchemaConfiguration.Type = SchemaConfiguration.self

  public static func objectType(forTypename typename: String) -> ApolloAPI.Object? {
    switch typename {
    case "Mutation": return GitHubGraphQLAPI.Objects.Mutation
    case "UpdateUserListsForItemPayload": return GitHubGraphQLAPI.Objects.UpdateUserListsForItemPayload
    case "UserList": return GitHubGraphQLAPI.Objects.UserList
    case "Achievement": return GitHubGraphQLAPI.Objects.Achievement
    case "Bot": return GitHubGraphQLAPI.Objects.Bot
    case "EnterpriseUserAccount": return GitHubGraphQLAPI.Objects.EnterpriseUserAccount
    case "Mannequin": return GitHubGraphQLAPI.Objects.Mannequin
    case "Organization": return GitHubGraphQLAPI.Objects.Organization
    case "Repository": return GitHubGraphQLAPI.Objects.Repository
    case "User": return GitHubGraphQLAPI.Objects.User
    case "Issue": return GitHubGraphQLAPI.Objects.Issue
    case "PullRequest": return GitHubGraphQLAPI.Objects.PullRequest
    case "Discussion": return GitHubGraphQLAPI.Objects.Discussion
    case "CommitComment": return GitHubGraphQLAPI.Objects.CommitComment
    case "DiscussionComment": return GitHubGraphQLAPI.Objects.DiscussionComment
    case "GistComment": return GitHubGraphQLAPI.Objects.GistComment
    case "IssueComment": return GitHubGraphQLAPI.Objects.IssueComment
    case "Project": return GitHubGraphQLAPI.Objects.Project
    case "ProjectNext": return GitHubGraphQLAPI.Objects.ProjectNext
    case "ProjectV2": return GitHubGraphQLAPI.Objects.ProjectV2
    case "PullRequestReview": return GitHubGraphQLAPI.Objects.PullRequestReview
    case "PullRequestReviewComment": return GitHubGraphQLAPI.Objects.PullRequestReviewComment
    case "Release": return GitHubGraphQLAPI.Objects.Release
    case "RepositoryAdvisory": return GitHubGraphQLAPI.Objects.RepositoryAdvisory
    case "RepositoryAdvisoryComment": return GitHubGraphQLAPI.Objects.RepositoryAdvisoryComment
    case "CommitCommentThread": return GitHubGraphQLAPI.Objects.CommitCommentThread
    case "DependabotUpdate": return GitHubGraphQLAPI.Objects.DependabotUpdate
    case "DiscussionCategory": return GitHubGraphQLAPI.Objects.DiscussionCategory
    case "PinnedDiscussion": return GitHubGraphQLAPI.Objects.PinnedDiscussion
    case "PullRequestCommitCommentThread": return GitHubGraphQLAPI.Objects.PullRequestCommitCommentThread
    case "RepositoryDependabotAlertsThread": return GitHubGraphQLAPI.Objects.RepositoryDependabotAlertsThread
    case "RepositoryVulnerabilityAlert": return GitHubGraphQLAPI.Objects.RepositoryVulnerabilityAlert
    case "TeamDiscussion": return GitHubGraphQLAPI.Objects.TeamDiscussion
    case "Commit": return GitHubGraphQLAPI.Objects.Commit
    case "Blob": return GitHubGraphQLAPI.Objects.Blob
    case "Tag": return GitHubGraphQLAPI.Objects.Tag
    case "Tree": return GitHubGraphQLAPI.Objects.Tree
    case "Team": return GitHubGraphQLAPI.Objects.Team
    case "TeamDiscussionComment": return GitHubGraphQLAPI.Objects.TeamDiscussionComment
    case "Milestone": return GitHubGraphQLAPI.Objects.Milestone
    case "Gist": return GitHubGraphQLAPI.Objects.Gist
    case "Topic": return GitHubGraphQLAPI.Objects.Topic
    case "Enterprise": return GitHubGraphQLAPI.Objects.Enterprise
    case "CheckRun": return GitHubGraphQLAPI.Objects.CheckRun
    case "StatusContext": return GitHubGraphQLAPI.Objects.StatusContext
    case "ClosedEvent": return GitHubGraphQLAPI.Objects.ClosedEvent
    case "ConvertToDraftEvent": return GitHubGraphQLAPI.Objects.ConvertToDraftEvent
    case "CrossReferencedEvent": return GitHubGraphQLAPI.Objects.CrossReferencedEvent
    case "MergedEvent": return GitHubGraphQLAPI.Objects.MergedEvent
    case "PullRequestCommit": return GitHubGraphQLAPI.Objects.PullRequestCommit
    case "ReadyForReviewEvent": return GitHubGraphQLAPI.Objects.ReadyForReviewEvent
    case "RepositoryTopic": return GitHubGraphQLAPI.Objects.RepositoryTopic
    case "ReviewDismissedEvent": return GitHubGraphQLAPI.Objects.ReviewDismissedEvent
    case "Workflow": return GitHubGraphQLAPI.Objects.Workflow
    case "WorkflowRun": return GitHubGraphQLAPI.Objects.WorkflowRun
    case "WorkflowRunFile": return GitHubGraphQLAPI.Objects.WorkflowRunFile
    case "AchievementTier": return GitHubGraphQLAPI.Objects.AchievementTier
    case "AddedToMergeQueueEvent": return GitHubGraphQLAPI.Objects.AddedToMergeQueueEvent
    case "AddedToProjectEvent": return GitHubGraphQLAPI.Objects.AddedToProjectEvent
    case "App": return GitHubGraphQLAPI.Objects.App
    case "AssignedEvent": return GitHubGraphQLAPI.Objects.AssignedEvent
    case "AutoMergeDisabledEvent": return GitHubGraphQLAPI.Objects.AutoMergeDisabledEvent
    case "AutoMergeEnabledEvent": return GitHubGraphQLAPI.Objects.AutoMergeEnabledEvent
    case "AutoRebaseEnabledEvent": return GitHubGraphQLAPI.Objects.AutoRebaseEnabledEvent
    case "AutoSquashEnabledEvent": return GitHubGraphQLAPI.Objects.AutoSquashEnabledEvent
    case "AutomaticBaseChangeFailedEvent": return GitHubGraphQLAPI.Objects.AutomaticBaseChangeFailedEvent
    case "AutomaticBaseChangeSucceededEvent": return GitHubGraphQLAPI.Objects.AutomaticBaseChangeSucceededEvent
    case "BaseRefChangedEvent": return GitHubGraphQLAPI.Objects.BaseRefChangedEvent
    case "BaseRefDeletedEvent": return GitHubGraphQLAPI.Objects.BaseRefDeletedEvent
    case "BaseRefForcePushedEvent": return GitHubGraphQLAPI.Objects.BaseRefForcePushedEvent
    case "BranchProtectionRule": return GitHubGraphQLAPI.Objects.BranchProtectionRule
    case "BypassForcePushAllowance": return GitHubGraphQLAPI.Objects.BypassForcePushAllowance
    case "BypassPullRequestAllowance": return GitHubGraphQLAPI.Objects.BypassPullRequestAllowance
    case "CWE": return GitHubGraphQLAPI.Objects.CWE
    case "CheckSuite": return GitHubGraphQLAPI.Objects.CheckSuite
    case "CodeOfConduct": return GitHubGraphQLAPI.Objects.CodeOfConduct
    case "CommentDeletedEvent": return GitHubGraphQLAPI.Objects.CommentDeletedEvent
    case "Comparison": return GitHubGraphQLAPI.Objects.Comparison
    case "ConnectedEvent": return GitHubGraphQLAPI.Objects.ConnectedEvent
    case "ConvertedNoteToIssueEvent": return GitHubGraphQLAPI.Objects.ConvertedNoteToIssueEvent
    case "ConvertedToDiscussionEvent": return GitHubGraphQLAPI.Objects.ConvertedToDiscussionEvent
    case "DemilestonedEvent": return GitHubGraphQLAPI.Objects.DemilestonedEvent
    case "DeployKey": return GitHubGraphQLAPI.Objects.DeployKey
    case "DeployedEvent": return GitHubGraphQLAPI.Objects.DeployedEvent
    case "Deployment": return GitHubGraphQLAPI.Objects.Deployment
    case "DeploymentEnvironmentChangedEvent": return GitHubGraphQLAPI.Objects.DeploymentEnvironmentChangedEvent
    case "DeploymentReview": return GitHubGraphQLAPI.Objects.DeploymentReview
    case "DeploymentStatus": return GitHubGraphQLAPI.Objects.DeploymentStatus
    case "DisconnectedEvent": return GitHubGraphQLAPI.Objects.DisconnectedEvent
    case "DiscussionPoll": return GitHubGraphQLAPI.Objects.DiscussionPoll
    case "DiscussionPollOption": return GitHubGraphQLAPI.Objects.DiscussionPollOption
    case "DraftIssue": return GitHubGraphQLAPI.Objects.DraftIssue
    case "EnterpriseAdministratorInvitation": return GitHubGraphQLAPI.Objects.EnterpriseAdministratorInvitation
    case "EnterpriseIdentityProvider": return GitHubGraphQLAPI.Objects.EnterpriseIdentityProvider
    case "EnterpriseRepositoryInfo": return GitHubGraphQLAPI.Objects.EnterpriseRepositoryInfo
    case "EnterpriseServerInstallation": return GitHubGraphQLAPI.Objects.EnterpriseServerInstallation
    case "EnterpriseServerUserAccount": return GitHubGraphQLAPI.Objects.EnterpriseServerUserAccount
    case "EnterpriseServerUserAccountEmail": return GitHubGraphQLAPI.Objects.EnterpriseServerUserAccountEmail
    case "EnterpriseServerUserAccountsUpload": return GitHubGraphQLAPI.Objects.EnterpriseServerUserAccountsUpload
    case "Environment": return GitHubGraphQLAPI.Objects.Environment
    case "ExternalIdentity": return GitHubGraphQLAPI.Objects.ExternalIdentity
    case "HeadRefDeletedEvent": return GitHubGraphQLAPI.Objects.HeadRefDeletedEvent
    case "HeadRefForcePushedEvent": return GitHubGraphQLAPI.Objects.HeadRefForcePushedEvent
    case "HeadRefRestoredEvent": return GitHubGraphQLAPI.Objects.HeadRefRestoredEvent
    case "IpAllowListEntry": return GitHubGraphQLAPI.Objects.IpAllowListEntry
    case "Label": return GitHubGraphQLAPI.Objects.Label
    case "LabeledEvent": return GitHubGraphQLAPI.Objects.LabeledEvent
    case "Language": return GitHubGraphQLAPI.Objects.Language
    case "License": return GitHubGraphQLAPI.Objects.License
    case "LinkedBranch": return GitHubGraphQLAPI.Objects.LinkedBranch
    case "LockedEvent": return GitHubGraphQLAPI.Objects.LockedEvent
    case "MarkedAsDuplicateEvent": return GitHubGraphQLAPI.Objects.MarkedAsDuplicateEvent
    case "MarketplaceCategory": return GitHubGraphQLAPI.Objects.MarketplaceCategory
    case "MarketplaceListing": return GitHubGraphQLAPI.Objects.MarketplaceListing
    case "MemberFeatureRequestNotification": return GitHubGraphQLAPI.Objects.MemberFeatureRequestNotification
    case "MembersCanDeleteReposClearAuditEntry": return GitHubGraphQLAPI.Objects.MembersCanDeleteReposClearAuditEntry
    case "MembersCanDeleteReposDisableAuditEntry": return GitHubGraphQLAPI.Objects.MembersCanDeleteReposDisableAuditEntry
    case "MembersCanDeleteReposEnableAuditEntry": return GitHubGraphQLAPI.Objects.MembersCanDeleteReposEnableAuditEntry
    case "OauthApplicationCreateAuditEntry": return GitHubGraphQLAPI.Objects.OauthApplicationCreateAuditEntry
    case "OrgOauthAppAccessApprovedAuditEntry": return GitHubGraphQLAPI.Objects.OrgOauthAppAccessApprovedAuditEntry
    case "OrgOauthAppAccessBlockedAuditEntry": return GitHubGraphQLAPI.Objects.OrgOauthAppAccessBlockedAuditEntry
    case "OrgOauthAppAccessDeniedAuditEntry": return GitHubGraphQLAPI.Objects.OrgOauthAppAccessDeniedAuditEntry
    case "OrgOauthAppAccessRequestedAuditEntry": return GitHubGraphQLAPI.Objects.OrgOauthAppAccessRequestedAuditEntry
    case "OrgOauthAppAccessUnblockedAuditEntry": return GitHubGraphQLAPI.Objects.OrgOauthAppAccessUnblockedAuditEntry
    case "OrgAddBillingManagerAuditEntry": return GitHubGraphQLAPI.Objects.OrgAddBillingManagerAuditEntry
    case "OrgAddMemberAuditEntry": return GitHubGraphQLAPI.Objects.OrgAddMemberAuditEntry
    case "OrgBlockUserAuditEntry": return GitHubGraphQLAPI.Objects.OrgBlockUserAuditEntry
    case "OrgConfigDisableCollaboratorsOnlyAuditEntry": return GitHubGraphQLAPI.Objects.OrgConfigDisableCollaboratorsOnlyAuditEntry
    case "OrgConfigEnableCollaboratorsOnlyAuditEntry": return GitHubGraphQLAPI.Objects.OrgConfigEnableCollaboratorsOnlyAuditEntry
    case "OrgCreateAuditEntry": return GitHubGraphQLAPI.Objects.OrgCreateAuditEntry
    case "OrgDisableOauthAppRestrictionsAuditEntry": return GitHubGraphQLAPI.Objects.OrgDisableOauthAppRestrictionsAuditEntry
    case "OrgDisableSamlAuditEntry": return GitHubGraphQLAPI.Objects.OrgDisableSamlAuditEntry
    case "OrgDisableTwoFactorRequirementAuditEntry": return GitHubGraphQLAPI.Objects.OrgDisableTwoFactorRequirementAuditEntry
    case "OrgEnableOauthAppRestrictionsAuditEntry": return GitHubGraphQLAPI.Objects.OrgEnableOauthAppRestrictionsAuditEntry
    case "OrgEnableSamlAuditEntry": return GitHubGraphQLAPI.Objects.OrgEnableSamlAuditEntry
    case "OrgEnableTwoFactorRequirementAuditEntry": return GitHubGraphQLAPI.Objects.OrgEnableTwoFactorRequirementAuditEntry
    case "OrgInviteMemberAuditEntry": return GitHubGraphQLAPI.Objects.OrgInviteMemberAuditEntry
    case "OrgInviteToBusinessAuditEntry": return GitHubGraphQLAPI.Objects.OrgInviteToBusinessAuditEntry
    case "OrgRemoveBillingManagerAuditEntry": return GitHubGraphQLAPI.Objects.OrgRemoveBillingManagerAuditEntry
    case "OrgRemoveMemberAuditEntry": return GitHubGraphQLAPI.Objects.OrgRemoveMemberAuditEntry
    case "OrgRemoveOutsideCollaboratorAuditEntry": return GitHubGraphQLAPI.Objects.OrgRemoveOutsideCollaboratorAuditEntry
    case "OrgRestoreMemberAuditEntry": return GitHubGraphQLAPI.Objects.OrgRestoreMemberAuditEntry
    case "OrgRestoreMemberMembershipOrganizationAuditEntryData": return GitHubGraphQLAPI.Objects.OrgRestoreMemberMembershipOrganizationAuditEntryData
    case "OrgUnblockUserAuditEntry": return GitHubGraphQLAPI.Objects.OrgUnblockUserAuditEntry
    case "OrgUpdateDefaultRepositoryPermissionAuditEntry": return GitHubGraphQLAPI.Objects.OrgUpdateDefaultRepositoryPermissionAuditEntry
    case "OrgUpdateMemberAuditEntry": return GitHubGraphQLAPI.Objects.OrgUpdateMemberAuditEntry
    case "OrgUpdateMemberRepositoryCreationPermissionAuditEntry": return GitHubGraphQLAPI.Objects.OrgUpdateMemberRepositoryCreationPermissionAuditEntry
    case "OrgUpdateMemberRepositoryInvitationPermissionAuditEntry": return GitHubGraphQLAPI.Objects.OrgUpdateMemberRepositoryInvitationPermissionAuditEntry
    case "PrivateRepositoryForkingDisableAuditEntry": return GitHubGraphQLAPI.Objects.PrivateRepositoryForkingDisableAuditEntry
    case "OrgRestoreMemberMembershipRepositoryAuditEntryData": return GitHubGraphQLAPI.Objects.OrgRestoreMemberMembershipRepositoryAuditEntryData
    case "PrivateRepositoryForkingEnableAuditEntry": return GitHubGraphQLAPI.Objects.PrivateRepositoryForkingEnableAuditEntry
    case "RepoAccessAuditEntry": return GitHubGraphQLAPI.Objects.RepoAccessAuditEntry
    case "RepoAddMemberAuditEntry": return GitHubGraphQLAPI.Objects.RepoAddMemberAuditEntry
    case "RepoAddTopicAuditEntry": return GitHubGraphQLAPI.Objects.RepoAddTopicAuditEntry
    case "RepoRemoveTopicAuditEntry": return GitHubGraphQLAPI.Objects.RepoRemoveTopicAuditEntry
    case "RepoArchivedAuditEntry": return GitHubGraphQLAPI.Objects.RepoArchivedAuditEntry
    case "RepoChangeMergeSettingAuditEntry": return GitHubGraphQLAPI.Objects.RepoChangeMergeSettingAuditEntry
    case "RepoConfigDisableAnonymousGitAccessAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigDisableAnonymousGitAccessAuditEntry
    case "RepoConfigDisableCollaboratorsOnlyAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigDisableCollaboratorsOnlyAuditEntry
    case "RepoConfigDisableContributorsOnlyAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigDisableContributorsOnlyAuditEntry
    case "RepoConfigDisableSockpuppetDisallowedAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigDisableSockpuppetDisallowedAuditEntry
    case "RepoConfigEnableAnonymousGitAccessAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigEnableAnonymousGitAccessAuditEntry
    case "RepoConfigEnableCollaboratorsOnlyAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigEnableCollaboratorsOnlyAuditEntry
    case "RepoConfigEnableContributorsOnlyAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigEnableContributorsOnlyAuditEntry
    case "RepoConfigEnableSockpuppetDisallowedAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigEnableSockpuppetDisallowedAuditEntry
    case "RepoConfigLockAnonymousGitAccessAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigLockAnonymousGitAccessAuditEntry
    case "RepoConfigUnlockAnonymousGitAccessAuditEntry": return GitHubGraphQLAPI.Objects.RepoConfigUnlockAnonymousGitAccessAuditEntry
    case "RepoCreateAuditEntry": return GitHubGraphQLAPI.Objects.RepoCreateAuditEntry
    case "RepoDestroyAuditEntry": return GitHubGraphQLAPI.Objects.RepoDestroyAuditEntry
    case "RepoRemoveMemberAuditEntry": return GitHubGraphQLAPI.Objects.RepoRemoveMemberAuditEntry
    case "TeamAddRepositoryAuditEntry": return GitHubGraphQLAPI.Objects.TeamAddRepositoryAuditEntry
    case "OrgRestoreMemberMembershipTeamAuditEntryData": return GitHubGraphQLAPI.Objects.OrgRestoreMemberMembershipTeamAuditEntryData
    case "TeamAddMemberAuditEntry": return GitHubGraphQLAPI.Objects.TeamAddMemberAuditEntry
    case "TeamChangeParentTeamAuditEntry": return GitHubGraphQLAPI.Objects.TeamChangeParentTeamAuditEntry
    case "TeamRemoveMemberAuditEntry": return GitHubGraphQLAPI.Objects.TeamRemoveMemberAuditEntry
    case "TeamRemoveRepositoryAuditEntry": return GitHubGraphQLAPI.Objects.TeamRemoveRepositoryAuditEntry
    case "RepositoryVisibilityChangeDisableAuditEntry": return GitHubGraphQLAPI.Objects.RepositoryVisibilityChangeDisableAuditEntry
    case "RepositoryVisibilityChangeEnableAuditEntry": return GitHubGraphQLAPI.Objects.RepositoryVisibilityChangeEnableAuditEntry
    case "MentionedEvent": return GitHubGraphQLAPI.Objects.MentionedEvent
    case "MergeQueue": return GitHubGraphQLAPI.Objects.MergeQueue
    case "MergeQueueEntry": return GitHubGraphQLAPI.Objects.MergeQueueEntry
    case "MigrationSource": return GitHubGraphQLAPI.Objects.MigrationSource
    case "MilestonedEvent": return GitHubGraphQLAPI.Objects.MilestonedEvent
    case "MobilePushNotificationSchedule": return GitHubGraphQLAPI.Objects.MobilePushNotificationSchedule
    case "MovedColumnsInProjectEvent": return GitHubGraphQLAPI.Objects.MovedColumnsInProjectEvent
    case "NotificationFilter": return GitHubGraphQLAPI.Objects.NotificationFilter
    case "NotificationThread": return GitHubGraphQLAPI.Objects.NotificationThread
    case "OIDCProvider": return GitHubGraphQLAPI.Objects.OIDCProvider
    case "OrganizationIdentityProvider": return GitHubGraphQLAPI.Objects.OrganizationIdentityProvider
    case "OrganizationInvitation": return GitHubGraphQLAPI.Objects.OrganizationInvitation
    case "OrganizationMigration": return GitHubGraphQLAPI.Objects.OrganizationMigration
    case "Package": return GitHubGraphQLAPI.Objects.Package
    case "PackageFile": return GitHubGraphQLAPI.Objects.PackageFile
    case "PackageTag": return GitHubGraphQLAPI.Objects.PackageTag
    case "PackageVersion": return GitHubGraphQLAPI.Objects.PackageVersion
    case "Patch": return GitHubGraphQLAPI.Objects.Patch
    case "PinnedEvent": return GitHubGraphQLAPI.Objects.PinnedEvent
    case "PinnedIssue": return GitHubGraphQLAPI.Objects.PinnedIssue
    case "ProjectCard": return GitHubGraphQLAPI.Objects.ProjectCard
    case "ProjectColumn": return GitHubGraphQLAPI.Objects.ProjectColumn
    case "ProjectNextField": return GitHubGraphQLAPI.Objects.ProjectNextField
    case "ProjectNextIterationField": return GitHubGraphQLAPI.Objects.ProjectNextIterationField
    case "ProjectNextSingleSelectField": return GitHubGraphQLAPI.Objects.ProjectNextSingleSelectField
    case "ProjectNextItem": return GitHubGraphQLAPI.Objects.ProjectNextItem
    case "ProjectNextItemFieldValue": return GitHubGraphQLAPI.Objects.ProjectNextItemFieldValue
    case "ProjectV2Field": return GitHubGraphQLAPI.Objects.ProjectV2Field
    case "ProjectV2IterationField": return GitHubGraphQLAPI.Objects.ProjectV2IterationField
    case "ProjectV2SingleSelectField": return GitHubGraphQLAPI.Objects.ProjectV2SingleSelectField
    case "ProjectV2Item": return GitHubGraphQLAPI.Objects.ProjectV2Item
    case "ProjectV2ItemFieldDateValue": return GitHubGraphQLAPI.Objects.ProjectV2ItemFieldDateValue
    case "ProjectV2ItemFieldIterationValue": return GitHubGraphQLAPI.Objects.ProjectV2ItemFieldIterationValue
    case "ProjectV2ItemFieldNumberValue": return GitHubGraphQLAPI.Objects.ProjectV2ItemFieldNumberValue
    case "ProjectV2ItemFieldSingleSelectValue": return GitHubGraphQLAPI.Objects.ProjectV2ItemFieldSingleSelectValue
    case "ProjectV2ItemFieldTextValue": return GitHubGraphQLAPI.Objects.ProjectV2ItemFieldTextValue
    case "ProjectV2View": return GitHubGraphQLAPI.Objects.ProjectV2View
    case "ProjectV2Workflow": return GitHubGraphQLAPI.Objects.ProjectV2Workflow
    case "ProjectView": return GitHubGraphQLAPI.Objects.ProjectView
    case "PublicKey": return GitHubGraphQLAPI.Objects.PublicKey
    case "PullRequestReviewThread": return GitHubGraphQLAPI.Objects.PullRequestReviewThread
    case "PullRequestThread": return GitHubGraphQLAPI.Objects.PullRequestThread
    case "Push": return GitHubGraphQLAPI.Objects.Push
    case "PushAllowance": return GitHubGraphQLAPI.Objects.PushAllowance
    case "Reaction": return GitHubGraphQLAPI.Objects.Reaction
    case "Ref": return GitHubGraphQLAPI.Objects.Ref
    case "ReferencedEvent": return GitHubGraphQLAPI.Objects.ReferencedEvent
    case "ReleaseAsset": return GitHubGraphQLAPI.Objects.ReleaseAsset
    case "RemovedFromMergeQueueEvent": return GitHubGraphQLAPI.Objects.RemovedFromMergeQueueEvent
    case "RemovedFromProjectEvent": return GitHubGraphQLAPI.Objects.RemovedFromProjectEvent
    case "RenamedTitleEvent": return GitHubGraphQLAPI.Objects.RenamedTitleEvent
    case "ReopenedEvent": return GitHubGraphQLAPI.Objects.ReopenedEvent
    case "RepositoryInvitation": return GitHubGraphQLAPI.Objects.RepositoryInvitation
    case "RepositoryMigration": return GitHubGraphQLAPI.Objects.RepositoryMigration
    case "RepositoryRule": return GitHubGraphQLAPI.Objects.RepositoryRule
    case "RepositoryRuleset": return GitHubGraphQLAPI.Objects.RepositoryRuleset
    case "RepositoryRulesetBypassActor": return GitHubGraphQLAPI.Objects.RepositoryRulesetBypassActor
    case "RequiredStatusCheck": return GitHubGraphQLAPI.Objects.RequiredStatusCheck
    case "ReviewDismissalAllowance": return GitHubGraphQLAPI.Objects.ReviewDismissalAllowance
    case "ReviewRequest": return GitHubGraphQLAPI.Objects.ReviewRequest
    case "ReviewRequestRemovedEvent": return GitHubGraphQLAPI.Objects.ReviewRequestRemovedEvent
    case "ReviewRequestedEvent": return GitHubGraphQLAPI.Objects.ReviewRequestedEvent
    case "SavedReply": return GitHubGraphQLAPI.Objects.SavedReply
    case "SearchShortcut": return GitHubGraphQLAPI.Objects.SearchShortcut
    case "TeamSearchShortcut": return GitHubGraphQLAPI.Objects.TeamSearchShortcut
    case "SecurityAdvisory": return GitHubGraphQLAPI.Objects.SecurityAdvisory
    case "SponsorsActivity": return GitHubGraphQLAPI.Objects.SponsorsActivity
    case "SponsorsListing": return GitHubGraphQLAPI.Objects.SponsorsListing
    case "SponsorsListingFeaturedItem": return GitHubGraphQLAPI.Objects.SponsorsListingFeaturedItem
    case "SponsorsTier": return GitHubGraphQLAPI.Objects.SponsorsTier
    case "Sponsorship": return GitHubGraphQLAPI.Objects.Sponsorship
    case "SponsorshipNewsletter": return GitHubGraphQLAPI.Objects.SponsorshipNewsletter
    case "Status": return GitHubGraphQLAPI.Objects.Status
    case "StatusCheckRollup": return GitHubGraphQLAPI.Objects.StatusCheckRollup
    case "SubscribedEvent": return GitHubGraphQLAPI.Objects.SubscribedEvent
    case "TeamDashboard": return GitHubGraphQLAPI.Objects.TeamDashboard
    case "TransferredEvent": return GitHubGraphQLAPI.Objects.TransferredEvent
    case "UnassignedEvent": return GitHubGraphQLAPI.Objects.UnassignedEvent
    case "UnlabeledEvent": return GitHubGraphQLAPI.Objects.UnlabeledEvent
    case "UnlockedEvent": return GitHubGraphQLAPI.Objects.UnlockedEvent
    case "UnmarkedAsDuplicateEvent": return GitHubGraphQLAPI.Objects.UnmarkedAsDuplicateEvent
    case "UnpinnedEvent": return GitHubGraphQLAPI.Objects.UnpinnedEvent
    case "UnsubscribedEvent": return GitHubGraphQLAPI.Objects.UnsubscribedEvent
    case "UserBlockedEvent": return GitHubGraphQLAPI.Objects.UserBlockedEvent
    case "UserContentEdit": return GitHubGraphQLAPI.Objects.UserContentEdit
    case "UserDashboard": return GitHubGraphQLAPI.Objects.UserDashboard
    case "UserStatus": return GitHubGraphQLAPI.Objects.UserStatus
    case "VerifiableDomain": return GitHubGraphQLAPI.Objects.VerifiableDomain
    case "UserListItemsConnection": return GitHubGraphQLAPI.Objects.UserListItemsConnection
    case "UserListConnection": return GitHubGraphQLAPI.Objects.UserListConnection
    case "Query": return GitHubGraphQLAPI.Objects.Query
    case "IssueTemplate": return GitHubGraphQLAPI.Objects.IssueTemplate
    case "LabelConnection": return GitHubGraphQLAPI.Objects.LabelConnection
    case "UserConnection": return GitHubGraphQLAPI.Objects.UserConnection
    case "RepositoryContactLink": return GitHubGraphQLAPI.Objects.RepositoryContactLink
    case "CommitHistoryConnection": return GitHubGraphQLAPI.Objects.CommitHistoryConnection
    case "IssueConnection": return GitHubGraphQLAPI.Objects.IssueConnection
    case "ProjectV2Connection": return GitHubGraphQLAPI.Objects.ProjectV2Connection
    case "LicenseRule": return GitHubGraphQLAPI.Objects.LicenseRule
    case "MilestoneConnection": return GitHubGraphQLAPI.Objects.MilestoneConnection
    case "PullRequestConnection": return GitHubGraphQLAPI.Objects.PullRequestConnection
    case "RefConnection": return GitHubGraphQLAPI.Objects.RefConnection
    case "RepositoryReadme": return GitHubGraphQLAPI.Objects.RepositoryReadme
    case "RepositoryTopicConnection": return GitHubGraphQLAPI.Objects.RepositoryTopicConnection
    case "MergeQueueEntryConnection": return GitHubGraphQLAPI.Objects.MergeQueueEntryConnection
    case "ReleaseConnection": return GitHubGraphQLAPI.Objects.ReleaseConnection
    case "UserListSuggestion": return GitHubGraphQLAPI.Objects.UserListSuggestion
    case "StarredRepositoryConnection": return GitHubGraphQLAPI.Objects.StarredRepositoryConnection
    case "PageInfo": return GitHubGraphQLAPI.Objects.PageInfo
    case "Feed": return GitHubGraphQLAPI.Objects.Feed
    case "FeedFilter": return GitHubGraphQLAPI.Objects.FeedFilter
    case "FeedItemConnection": return GitHubGraphQLAPI.Objects.FeedItemConnection
    case "AddedToListFeedItem": return GitHubGraphQLAPI.Objects.AddedToListFeedItem
    case "BecameSponsorableFeedItem": return GitHubGraphQLAPI.Objects.BecameSponsorableFeedItem
    case "CreatedDiscussionFeedItem": return GitHubGraphQLAPI.Objects.CreatedDiscussionFeedItem
    case "CreatedRepositoryFeedItem": return GitHubGraphQLAPI.Objects.CreatedRepositoryFeedItem
    case "FollowRecommendationFeedItem": return GitHubGraphQLAPI.Objects.FollowRecommendationFeedItem
    case "FollowedUserFeedItem": return GitHubGraphQLAPI.Objects.FollowedUserFeedItem
    case "ForkedRepositoryFeedItem": return GitHubGraphQLAPI.Objects.ForkedRepositoryFeedItem
    case "MemberAddToRepositoryFeedItem": return GitHubGraphQLAPI.Objects.MemberAddToRepositoryFeedItem
    case "MergedPullRequestFeedItem": return GitHubGraphQLAPI.Objects.MergedPullRequestFeedItem
    case "NearSponsorsGoalFeedItem": return GitHubGraphQLAPI.Objects.NearSponsorsGoalFeedItem
    case "PublishedReleaseFeedItem": return GitHubGraphQLAPI.Objects.PublishedReleaseFeedItem
    case "RepositoryRecommendationFeedItem": return GitHubGraphQLAPI.Objects.RepositoryRecommendationFeedItem
    case "SponsoredUserFeedItem": return GitHubGraphQLAPI.Objects.SponsoredUserFeedItem
    case "StarredRepositoryFeedItem": return GitHubGraphQLAPI.Objects.StarredRepositoryFeedItem
    case "ReactionGroup": return GitHubGraphQLAPI.Objects.ReactionGroup
    case "ReactorConnection": return GitHubGraphQLAPI.Objects.ReactorConnection
    case "RepositoryConnection": return GitHubGraphQLAPI.Objects.RepositoryConnection
    default: return nil
    }
  }
}

public enum Objects {}
public enum Interfaces {}
public enum Unions {}
